### ISSUE TITLE
프로젝트명 변경

### ISSUE THREAD

**Issue by holyPigeon** [2024-Open-Source-SW-Practice/Team-Project-Room-Reservation-Server#5]
### 📄 설명
프로젝트명이 너무 길어서 바꾸려고 합니다.
Team-Project-Room-Reservation -> TeamPu

### ✅ 작업할 내용
- [x] 프로젝트명 관련 패키지명, 파일명을 모두 변경합니다.
 
### ⏰ 추정 시간
1시간

**Comment by Muokok** [comment]
ㄷㄷ 이 시간에

**Comment by ahyeonkong** [comment]
팀푸 귀엽네요 ㅋ.ㅋ

**Comment by holyPigeon** [comment]
??? 다 안 자네 ㅋㅋㅋㅋ
